{% set name = "pyvmomi" %}
{% set version = "7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e1802494a6bbc4c3be36afd11f730e4a85094b2074e9d5806a47131cf788232

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.3.0
    - six >=1.7.3

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - pyVim
    - pyVmomi
  commands:
    - pip check

about:
  home: https://github.com/vmware/pyvmomi
  license: Apache-2.0
  license_file: LICENSE
  summary: VMware vSphere Python SDK

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
    - maresb 
